version: '3.3'

services:
  jnote:
    container_name: jnote
    image: agitolyev/jnote:${VERSION:-latest}
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    expose:
      - "8888"
    volumes:
      - ~/git/jnote/data:/home/jovyan/work