version: 2
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: |
          VERSION=$CIRCLE_SHA1 docker-compose build

  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: "Push image"
          command: |
            docker login -u="${DOCKER_LOGIN}" -p="${DOCKER_LOGIN_PASSWORD}"
            VERSION=${CIRCLE_TAG:-dev-$CIRCLE_SHA1} docker-compose build
            VERSION=${CIRCLE_TAG:-dev-$CIRCLE_SHA1} docker-compose push
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test:
          context: circleci
          filters:
            tags:
              only: /.+/
      - deploy:
          context: circleci
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
